export const products = [
  {
    id: 1,
    name: "Anchor Full Cream Fresh Milk 1L",
    imageUrl: "/images/topsaverimages/anchor.png",
    price: 850.0,
    discountPrice: 900.0,
    stock: 100,
    type: "Dairy",
    date: "2023-01-01",
    brand: "Anchor",
    category: "teaandcoffee",
    tags: ["fresh", "dairy", "nutrition"],
  },
  {
    id: 2,
    name: "Fresh Organic Apples (Pack of 6)",
    imageUrl: "/images/topsaverimages/apples.png",
    price: 12.99,
    discountPrice: 14.99,
    stock: 0,
    type: "Produce",
    date: "2023-01-05",
    brand: "Organic Farms",
    category: "meat",
    tags: ["organic", "apples", "fresh"],
  },
  {
    id: 3,
    name: "Premium Coffee Beans 500g",
    imageUrl: "/images/topsaverimages/coffee.png",
    price: 19.99,
    discountPrice: 22.99,
    stock: 0,
    type: "Beverages",
    date: "2023-01-10",
    brand: "Premium Coffee Co.",
    category: "fruits",
    tags: ["coffee", "beans", "premium"],
  },
  {
    id: 4,
    name: "Organic Avocado Oil 250ml",
    imageUrl: "/images/topsaverimages/avocado-oil.png",
    price: 50,
    discountPrice: 17.5,
    stock: 20,
    type: "Cooking",
    date: "2023-01-15",
    brand: "Healthy Harvest",
    category: "teaandcoffee",
    tags: ["organic", "avocado oil", "cooking"],
  },
  // Add more products as needed
];
