export const products = [
  {
    id: 1,
    name: "Anchor Full Cream Fresh Milk 1L",
    imageUrl: "/images/topsaverimages/anchor.png",
    stars: 5,
    price: 850.0,
    priceOne: 800.0,
    priceTwo: 900.0,
    sizeOne: "1L",
    sizeTwo: "2L",
    secondPrice: 900.0,
    save: 50.0,
    stock: 100,
    type: "Dairy",
    date: "2023-01-01",
    life: "30 days",
    brand: "Anchor",
    category: "milkanddiaries",
    tags: ["fresh", "dairy", "nutrition"],
  },
  {
    id: 2,
    name: "Fresh Organic Apples (Pack of 6)",
    imageUrl: "/images/topsaverimages/apples.png",
    stars: 4,
    price: 12.99,
    priceOne: 11.99,
    priceTwo: 13.99,
    sizeOne: "6 apples",
    sizeTwo: "12 apples",
    secondPrice: 14.99,
    save: 2.0,
    stock: 50,
    type: "Produce",
    date: "2023-01-05",
    life: "7 days",
    brand: "Organic Farms",
    category: "Fruits",
    tags: ["organic", "apples", "fresh"],
  },
  {
    id: 3,
    name: "Premium Coffee Beans 500g",
    imageUrl: "/images/topsaverimages/coffee.png",
    stars: 5,
    price: 19.99,
    priceOne: 18.99,
    priceTwo: 21.99,
    sizeOne: "500g",
    sizeTwo: "1kg",
    secondPrice: 22.99,
    save: 3.0,
    stock: 30,
    type: "Beverages",
    date: "2023-01-10",
    life: "365 days",
    brand: "Premium Coffee Co.",
    category: "Coffee",
    tags: ["coffee", "beans", "premium"],
  },
  {
    id: 4,
    name: "Organic Avocado Oil 250ml",
    imageUrl: "/images/topsaverimages/avocado-oil.png",
    stars: 4,
    price: 15.5,
    priceOne: 14.5,
    priceTwo: 16.5,
    sizeOne: "250ml",
    sizeTwo: "500ml",
    secondPrice: 17.5,
    save: 2.0,
    stock: 20,
    type: "Cooking",
    date: "2023-01-15",
    life: "90 days",
    brand: "Healthy Harvest",
    category: "Oils",
    tags: ["organic", "avocado oil", "cooking"],
  },
  // Add more products as needed
];
